### ISSUE TITLE
About the dataset problem of "mmBody Benchmark"

### ISSUE THREAD

**Issue by yuyu19970716** [Chen3110/Chen3110.github.io#1]
Hello!
     I'm so sorry to bother you! Your paper "mmBody Benchmark: 3D Body Reconstruction Dataset and Analysis for Millimeter Wave Radar" did a great job! I want to do my own graduate project using your dataset is it okay? I didn't find an address where I can download this dataset, and my topic is ultimately also about 3D reconstruction of radar data. Can I download this dataset please?
     Thanks in advance!
     Very much looking forward to your reply! Good luck!

**Comment by Chen3110** [comment]
Thanks for your focus on our work. We will open the dataset after the conference of ACM MM2022.
Best wishes!
