### ISSUE TITLE
你好 我对你的工作很感兴趣 请问你什么时候共享你的mmbody数据集？

### ISSUE THREAD

**Issue by madgnot** [Chen3110/Chen3110.github.io#2]
你好，可以共享一下数据集吗

**Comment by Chen3110** [comment]
非常抱歉，我们现在在维护数据集的license，大概下周可以重新开放下载链接。开放之后会第一时间告知。

**Comment by madgnot** [comment]
好的，谢谢



------------------&nbsp;Original message&nbsp;------------------
From: "Chen3110"; 
Sendtime: Sunday, Dec 11, 2022 9:59 PM
To: "Chen3110/Chen3110.github.io"; 
Cc: ***@***.***>; "Author"; 
Subject: Re: [Chen3110/Chen3110.github.io] 你好 我对你的工作很感兴趣 请问你什么时候共享你的mmbody数据集？ (Issue #2)





 
非常抱歉，我们现在在维护数据集的license，大概下周可以重新开放下载链接。开放之后会第一时间告知。
